# Generated by Django 5.0.2 on 2024-02-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_donde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
